[package]
name = "pocket_cleaner"
version = "0.1.0"
authors = ["Bob Gardner <bob.hn.gardner@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.10"
actix-web = { version = "2.0.0", features = ["openssl"] }
url = "2.1.1"
serde = "1.0.104"
log = "0.4.8"
serde_json = "1.0.48"
actix-rt = "1.0.0"
