name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.7.5"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_COMMIT_MESSAGE: "pull-request-description"
          MERGE_LABELS: "!wip,ready-to-squash-and-merge"
          MERGE_METHOD: "squash"
          # CI takes several minutes, so only retry the merge
          # every 2 MIN = 120 SEC = 120000 MS
          MERGE_RETRY_SLEEP: 120000
