# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

name: Pocket Cleaner CI

on:
  pull_request:
    paths:
      - "!*"
      - ".github/workflows/pocket_cleaner.ci.yml"
      - "app/pocket_cleaner/**"
      - "!app/pocket_cleaner/.gitignore"
      - "!app/pocket_cleaner/**.md"
  push:
    branches: [master]
    paths:
      - "!*"
      - ".github/workflows/pocket_cleaner.ci.yml"
      - "app/pocket_cleaner/**"
      - "!app/pocket_cleaner/.gitignore"
      - "!app/pocket_cleaner/**.md"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Check
        run: cd app/pocket_cleaner && cargo check --release

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: test
        run: cd app/pocket_cleaner && cargo test --release

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - run: cd app/pocket_cleaner && cargo fmt -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - run: cd app/pocket_cleaner && cargo clippy -- -D warnings

  docker:
    name: Docker
    runs-on: ubuntu-latest
    if: github.event_name == "pull_request"
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: cd app/pocket_cleaner && docker build . --tag rgardner/memory-jogger/pocket_cleaner:$(date +%s)

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [check, test, fmt, clippy]
    if: github.event_name == "push" and github.ref == "refs/heads/master"
    steps:
      - uses: actions/checkout@v1
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push --app ${{ secrets.HEROKU_APP_NAME }} web
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release --app ${{ secrets.HEROKU_APP_NAME }} web
